### PR TITLE
Replace language arg by standard translation mechanism

### LINKED ISSUE #138: Use standard mechanisms to offer language options
epiCo currently proposes the output in English or Spanish in a number of functions. This is great to improve usability & adoption!

I think the current way to specify language could be improved by using R standard mechanisms (via the `gettext()` function) and automatically detecting the user language.

Benefits:

- from the user point of view, no need to manually specify the value of the `lang` argument in numerous function calls
- from a maintainer point of view, reduction of the code duplication and streamlining of the addition of new translations

It may be good to have global meeting on this at some point so we can start adding multilingual options to many Epiverse-TRACE packages in a standard way.

### PR DESCRIPTION
**Pull request by Bisaloo**
Fix #138 

Todo:

- [x] Move the Spanish translations to the `po/R-es.po` file
- [x] Possible remove the translation arg from `describe_ethnicity()` as well
- [x] Compile to `.po` files into `.mo` with `potools::po_compile()`
- [ ] Document how to get translated text in plots
- [ ] Document the breaking change in NEWS

@juan-umana @Juanmontenegro99, this is a starting point to fix #138 using what we discussed yesterday in the development meeting (https://michaelchirico.github.io/potools/). Could you have a look and take this PR from here by finalizing the todos if you agree with this change.

It removes a large portion of duplicated code so it's an important improvement in terms of maintainability

### CODE REVIEW

**Comment by juan-umana** [comment]
Thanks, @Bisaloo. The translation looks great and will be useful for Spanish-, Portuguese- and French-speaking countries in LAC also. We have some questions regarding the regional configuration of R that a user may have.

From what we understand, `potools` identifies the locale using Sys.getlocale() to choose the appropriate translation for the users. We also found that users can change their regional configuration using Sys.setlocale().

Then, when a user has its configuration in English (for expample) but wants to use epiCo (exclusively) in Spanish, without changing the configuration: should we ask the user to adjust their locale settings before using epiCo, or is it something we can handle within epiCo's functions?

**Comment by Bisaloo** [comment]
> Then, when a user has its configuration in English (for expample) but wants to use epiCo (exclusively) in Spanish, without changing the configuration: should we ask the user to adjust their locale settings before using epiCo, or is it something we can handle within epiCo's functions?

Not easily, because the expectation is that users would likely prefer having the same language for all packages.

If this assumption is not verified, we could work around it by:

- recommending the users use withr:
  ```r
  withr::with_language("es", epiCo:: ...)
  ```
- using the proposed infrastructure here to handle translations without code duplication but keep the `language` argument and use `withr::local_language("es")` internally within the epiCo source code

**Review by juan-umana — APPROVED** [review]

**Review by juan-umana — APPROVED** [review]

**Comment by juan-umana** [comment]
@Juanmontenegro99 I think the changed files are ok, as well as the translatons.

However, @Bisaloo, we have not been able to get the plot in the system configuration (spanish)

Here is an screenshot of R messages being displayed in spanish (after using the `Sys.setlocale("LC_ALL", "es_ES")` and/or `withr::local_language("es")`)

image

Could you help us reviewing the po files? Thanks!

**Comment by Bisaloo** [comment]
Thanks for the report! It should be fixed with [`22a77fb` (#140)](https://github.com/epiverse-trace/epiCo/pull/140/commits/22a77fb24359183b5f21fe3cd8c0d29def705f65).

**Pull request merged**
